# @package _group_
train: True # Boolean that describes whether we are training or testing using a trained model.
epochs: 50
batch_size: 256 # 512 in paper
learning_rate: 3e-3
optimiser: Adam
loss_fn: MSE
checkpoint_freq: 5 # How many epochs we should train for before checkpointing the model.
log_steps: 50 # How many gradient steps between each log point.
fine_tune: False # Whether or not we are fine-tuning on Shipston data.
date_range: [] # Custom date range for the train dataset, as a list of two strings.
mc_dropout: True # Whether or not to use MC Dropout to get output uncertainty.
